### ISSUE TITLE
reported: Native is not bound

### ISSUE THREAD

**Issue by panikajo** [Online-Fighting-League/OFL-AC#1]
hi i have error
Game cs:go
 [01] SourceMod (1.10.0.6492) by AlliedModders LLC

`L 03/26/2021 - 00:38:56: [SM] Exception reported: Native is not bound
L 03/26/2021 - 00:38:56: [SM] Blaming: OFLAntiCheat.smx
L 03/26/2021 - 00:38:56: [SM] Call stack trace:
L 03/26/2021 - 00:38:56: [SM]   [1] SBPP_BanPlayer
L 03/26/2021 - 00:38:56: [SM]   [2] Line 1272, plugin.sp::BanPlayer
L 03/26/2021 - 00:38:56: [SM]   [3] Line 439, plugin.sp::OnPlayerChangeTag
L 03/26/2021 - 00:38:56: [SM]   [4] Line 410, plugin.sp::OnClientCommandKeyValues`

**Comment by pel-ex** [comment]
Thanks, I will look into this and get back to you with a fix.

**Comment by pel-ex** [comment]
1.2.21 should contain a fix to this issue.
